### PR TITLE
Headers are encoded properly when they exceed 126 characters

### PR DESCRIPTION
**Pull request by cstar**
With the help of the cow_hpack module, headers over 126 chars do not fail anymore.

Previously, APNS would return:

```
 Got GOAWAY, COMPRESSION_ERROR, Last Stream: 1, Rest: decode only works with an entire header block! UnpooledSlicedByteBuf(ridx: 349, widx: 376, cap: 376/376, unwrapped: PooledUnsafeDirectByteBuf(ridx: 385, widx: 385, cap: 414))
``` 
When sending a key too long (over 110 chars)
And the pigeon lib timed out.

Now encoding is done properly and APNS returns:

```elixir
%Kadabra.Stream{body: "{\"reason\":\"BadDeviceToken\"}",
 headers: [{":status", "400"},
  {"apns-id", "746418F0-97B5-67E7-DB8D-69B9065CCAD1"}], id: 1}
```

### CODE REVIEW

**Comment by shawnbro** [comment]
Any chance of this being merged? I'm facing this same issue...

**Comment by hpopp** [comment]
I've been hesitant to straight up rip ninenine's source just to get this working, much less having a module named `cow_hpack`. I'll double-check everything later today and probably accept this PR as a temporary fix. Ideally I'd like a pure-elixir solution moving forward.

**Comment by cstar** [comment]
I totally understand your point. Feel free not to merge, users can use my hack while we find a proper way of address this. :)

**Comment by shawnbro** [comment]
Yeah definitely.  I was able to use cstar's fork as a temporary solution. Thanks.

**Comment by cstar** [comment]
I have changed my code to use the HPack.
Tell me what you think.

02441c9 contains a fix to enable interop with Cowboy 2.0.0-pre4
(I am writing a mock APNS and GCM server to do load testing of my solution)

**Comment by hpopp** [comment]
At first glance I like this much, much better. I'll properly walk through it later today and merge.

**Pull request merged**
